name: Build checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release, Debug

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "MSVC Debug"
          os: windows-latest
          build_type: "Debug"
        - name: "MSVC Release"
          os: windows-latest
          build_type: "Release"
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: Amadevus/pwsh-script@v2
      id: set-locale
      with:
        script: |
          'Set-WinSystemLocale en-US'
          'Set-WinUserLanguageList en-US'
    - name: Set Locale
      run: echo "${{steps.set-locale.outputs.result}}"
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DOPAL_BUILD_TESTS=ON -DOPAL_HARDENING=OFF

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}
      
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C ${{matrix.config.build_type}} --output-on-failure --verbose
